GET http://localhost:5000

### 회원가입
POST http://localhost:5000/api/v1/auth/register
Content-Type: application/json

{
  "username" : "tester",
  "email" : "test@test.com",
  "password" : "123123",
  "confirmPassword" : "123123"
}


### 로그인
POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
  "email" : "test@test.com",
  "password" : "123123"
}

### 모든 Todo 가져오기
GET http://localhost:5000/api/v1/todo
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNmJlYmFlNDljNDlhMWU0ZWE1YjA0NyIsInVzZXJuYW1lIjoi6rmA7LC97KSAIiwiaWF0IjoxNjUxMjM5OTEwLCJleHAiOjE2NTEzMjYzMTB9.y8bUmNXThhefzaEkGfGnwgpU_ijBJJnT7x27a3rfJrA

### 하나의 Todo 가져오기
GET http://localhost:5000/api/v1/todo/626bec0149c49a1e4ea5b053
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNmJlYmFlNDljNDlhMWU0ZWE1YjA0NyIsInVzZXJuYW1lIjoi6rmA7LC97KSAIiwiaWF0IjoxNjUxMjM5OTEwLCJleHAiOjE2NTEzMjYzMTB9.y8bUmNXThhefzaEkGfGnwgpU_ijBJJnT7x27a3rfJrA

### Todo 만들기
POST http://localhost:5000/api/v1/todo
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNmJlYmFlNDljNDlhMWU0ZWE1YjA0NyIsInVzZXJuYW1lIjoi6rmA7LC97KSAIiwiaWF0IjoxNjUxMjM5OTEwLCJleHAiOjE2NTEzMjYzMTB9.y8bUmNXThhefzaEkGfGnwgpU_ijBJJnT7x27a3rfJrA

{
  "title" : "아~~~~~ 드뎌했다",
  "description" : "테스트3요",
  "date" : "04282022"
}

### Todo 수정하기
PUT http://localhost:5000/api/v1/todo/626bd80c50d8fe53b2d618df
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNmJjM2JiYzY3ZDM0ZDFjMjU2ZjViZCIsInVzZXJuYW1lIjoidGVzdGVyIiwiaWF0IjoxNjUxMjI5OTM3LCJleHAiOjE2NTEzMTYzMzd9.LlM0Y-qssCX1O2QiJBLF5yhHbb5p3oExuxLtiISpRwY

{
  "title" : "수정된",
  "content" : "테스트요",
  "date" : "May 6 30"
}

### Todo 삭제하기
DELETE  http://localhost:5000/api/v1/todo/626bd7ef50d8fe53b2d618da
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNmJjM2JiYzY3ZDM0ZDFjMjU2ZjViZCIsInVzZXJuYW1lIjoidGVzdGVyIiwiaWF0IjoxNjUxMjI5OTM3LCJleHAiOjE2NTEzMTYzMzd9.LlM0Y-qssCX1O2QiJBLF5yhHbb5p3oExuxLtiISpRwY

