GET http://localhost:5000

### 회원가입
POST http://localhost:5000/api/v1/auth/register
Content-Type: application/json

{
  "username" : "tester",
  "email" : "test@test.com",
  "password" : "123123",
  "confirmPassword" : "123123"
}


### 로그인
POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
  "email" : "test@test.com",
  "password" : "123123"
}

### 모든 Todo 가져오기
GET http://localhost:5000/api/v1/todo
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNmQyODYwNDQzOWFlZjg2MGQ0NDc5MCIsInVzZXJuYW1lIjoi6rmA7LC97KSAIiwiaWF0IjoxNjUxMzIwOTUxLCJleHAiOjE2NTE0MDczNTF9.HBHVmnxcaNjLnxEjdupxIF6QZAPLlyUrCbq013QdlHw

### 하나의 Todo 가져오기
GET http://localhost:5000/api/v1/todo/626cf6274f68768bb6109196
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNmNmNWM5YmIyNjRkNjQwZDE5NTI1YyIsInVzZXJuYW1lIjoidGVzdGVyIiwiaWF0IjoxNjUxMzA5MDMzLCJleHAiOjE2NTEzOTU0MzN9.LT1OF72911VMPHHe8ZtiBMeGyAY2f1bXiNcTWOZ0z9M

### Todo 만들기
POST http://localhost:5000/api/v1/todo
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNmQyODYwNDQzOWFlZjg2MGQ0NDc5MCIsInVzZXJuYW1lIjoi6rmA7LC97KSAIiwiaWF0IjoxNjUxMzIwOTUxLCJleHAiOjE2NTE0MDczNTF9.HBHVmnxcaNjLnxEjdupxIF6QZAPLlyUrCbq013QdlHw

{
  "title" : "되나요",
  "description" : "ㅇㅇㅇ",
  "date" : "04282022"
}

### Todo 수정하기
PUT http://localhost:5000/api/v1/todo/626e2808faf75ad535fef14b
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNmQyODYwNDQzOWFlZjg2MGQ0NDc5MCIsInVzZXJuYW1lIjoi6rmA7LC97KSAIiwiaWF0IjoxNjUxMzIwOTUxLCJleHAiOjE2NTE0MDczNTF9.HBHVmnxcaNjLnxEjdupxIF6QZAPLlyUrCbq013QdlHw

{
  "title" : "수정했지asdasdasdasdasdasdasdasdasdasdasdasdasd비222332",
  "content" : "테스asdasdasdasdasdasdasd트요",
  "date" : "20220305"
}

### Todo 삭제하기
PUT http://localhost:5000/api/v1/todo
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNmQwZTc0Mjc4YTdmMTkyODg4MTY5NyIsInVzZXJuYW1lIjoidGVzdGVyIiwiaWF0IjoxNjUxMzE0MjkyLCJleHAiOjE2NTE0MDA2OTJ9.DuuSjz_zqW-EfXOVvgKuRxsv0JDkPo0dEzr0Cor2vnY

{
  "todoIds" : "626cf604cab9ba1e61231ca4"
}
