GET http://localhost:5000

### 회원가입
POST http://localhost:5000/api/v1/auth/register
Content-Type: application/json

{
  "username" : "tester",
  "email" : "test@test.com",
  "password" : "123123",
  "confirmPassword" : "123123"
}


### 로그인
POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
  "email" : "test@test.com",
  "password" : "123123"
}

### 모든 Todo 가져오기
GET http://localhost:5000/api/v1/todo
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNmE1OTIwNWI3OWE1YmNiMTI5NjY4ZSIsInVzZXJuYW1lIjoidGVzdGVyIiwiaWF0IjoxNjUxMTM2ODkxLCJleHAiOjE2NTEyMjMyOTF9.euf6fSfQ3k4FU2I19jfOnIsiPzb4vXTqDoqVaCzAc-Q

### 하나의 Todo 가져오기
GET http://localhost:5000/api/v1/todo/6266a06b4ae33ba79812db02
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNmE1OTIwNWI3OWE1YmNiMTI5NjY4ZSIsInVzZXJuYW1lIjoidGVzdGVyIiwiaWF0IjoxNjUxMTM2ODkxLCJleHAiOjE2NTEyMjMyOTF9.euf6fSfQ3k4FU2I19jfOnIsiPzb4vXTqDoqVaCzAc-Q

### Todo 만들기
POST http://localhost:5000/api/v1/todo
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNmE1OTIwNWI3OWE1YmNiMTI5NjY4ZSIsInVzZXJuYW1lIjoidGVzdGVyIiwiaWF0IjoxNjUxMTM2ODkxLCJleHAiOjE2NTEyMjMyOTF9.euf6fSfQ3k4FU2I19jfOnIsiPzb4vXTqDoqVaCzAc-Q

{
  "title" : "테스트",
  "content" : "테스트요",
  "date" : "04282022"
}

### Todo 수정하기
PUT http://localhost:5000/api/v1/todo/6266a06b4ae33ba79812db02
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNjY4NTIwYmQ3MmFhNzIxZTE5MmFlOSIsInVzZXJuYW1lIjoi6rmA7LC97KSAIiwiaWF0IjoxNjUwODkyMDIyLCJleHAiOjE2NTA4OTU2MjJ9.HUsmKZTl3HoEjKH4KM4Y9jAXepCvcv-KvsaHlYxq0T4

{
  "title" : "수정된",
  "content" : "테스트요",
  "date" : "May 6 30"
}

### Todo 삭제하기
DELETE  http://localhost:5000/api/v1/todo/62669e8dc2cfd9f4c002a51b
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNjY4NTIwYmQ3MmFhNzIxZTE5MmFlOSIsInVzZXJuYW1lIjoi6rmA7LC97KSAIiwiaWF0IjoxNjUwODkyMDIyLCJleHAiOjE2NTA4OTU2MjJ9.HUsmKZTl3HoEjKH4KM4Y9jAXepCvcv-KvsaHlYxq0T4

{
  "title" : "테스트",
  "content" : "테스트요",
  "date" : "2022 03 04"
}